#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════════════════
# gcp_setup.sh — Step 1 of 4 : One-time GCP project setup
# ══════════════════════════════════════════════════════════════════════════════
#
# What this does (run ONCE before any deployment):
#   1. Points gcloud at your project
#   2. Enables Vertex AI API only (Agent Engine deployment)
#   3. Uses an EXISTING GCS bucket — does NOT create a new one
#   4. Writes a .env.deploy file with your config for the next scripts
#
# NOTE: Bucket creation is SKIPPED — set GCS_STAGING_BUCKET to your
#       existing bucket name below before running.
#
# HOW TO RUN:
#   Option A — Google Cloud Shell (easiest, nothing to install):
#     Open https://shell.cloud.google.com
#     Upload this file → run:  bash gcp_setup.sh
#
#   Option B — Local terminal (needs gcloud CLI installed):
#     https://cloud.google.com/sdk/docs/install
#     Then run:  bash gcp_setup.sh
#
# ── Fill in these two values before running ───────────────────────────────────
GCP_PROJECT_ID=""          # ← paste your GCP project ID here  e.g. intellidraft-prod-123
GCP_REGION="asia-south1"
GCS_STAGING_BUCKET=""      # ← paste the existing GCS bucket name (WITHOUT gs://)  e.g. my-team-staging-bucket
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Validate required values ──────────────────────────────────────────────────
if [[ -z "$GCP_PROJECT_ID" ]]; then
  echo ""
  echo "✗  GCP_PROJECT_ID is empty!"
  echo "   Open this file and fill in GCP_PROJECT_ID at the top, then re-run."
  echo ""
  exit 1
fi

if [[ -z "$GCS_STAGING_BUCKET" ]]; then
  echo ""
  echo "✗  GCS_STAGING_BUCKET is empty!"
  echo "   Open this file and fill in GCS_STAGING_BUCKET at the top (WITHOUT gs://),"
  echo "   then re-run."
  echo ""
  exit 1
fi

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║   IntelliDraft — GCP One-time Setup (Step 1/4)      ║"
echo "╚══════════════════════════════════════════════════════╝"
echo "  Project : ${GCP_PROJECT_ID}"
echo "  Region  : ${GCP_REGION}"
echo "  Bucket  : gs://${GCS_STAGING_BUCKET}"
echo ""

# ── 1. Set active project ─────────────────────────────────────────────────────
echo "▶ 1/4 — Setting active project …"
gcloud config set project "${GCP_PROJECT_ID}"
gcloud config set run/region "${GCP_REGION}"
echo "  ✓ Active project: ${GCP_PROJECT_ID}"
echo ""

# ── 2. Enable APIs ────────────────────────────────────────────────────────────
echo "▶ 2/4 — Enabling required GCP APIs …"
echo "  (takes ~1-2 min on a fresh project)"
echo ""

gcloud services enable \
  aiplatform.googleapis.com \
  storage.googleapis.com \
  --project="${GCP_PROJECT_ID}"

echo "  ✓ APIs enabled:"
echo "     • Vertex AI / Gemini Enterprise Agent Platform  (Agent Engine + Gemini)"
echo "     • Cloud Storage                                 (staging bucket access)"
echo ""
echo "  Note: Cloud Run, Cloud Build, Artifact Registry APIs are skipped"
echo "        for now — only Agent Engine is being deployed in this step."
echo ""

# ── 3. Verify existing GCS bucket access ─────────────────────────────────────
echo "▶ 3/4 — Verifying access to existing GCS bucket …"

if gcloud storage ls "gs://${GCS_STAGING_BUCKET}" &>/dev/null; then
  echo "  ✓ Bucket accessible: gs://${GCS_STAGING_BUCKET}"
else
  echo "  ✗  Cannot access gs://${GCS_STAGING_BUCKET}"
  echo "     Ask the bucket owner to grant you this role on the bucket:"
  echo "     gcloud storage buckets add-iam-policy-binding gs://${GCS_STAGING_BUCKET} \\"
  echo "       --member=user:\$(gcloud config get-value account) \\"
  echo "       --role=\"roles/storage.objectAdmin\""
  exit 1
fi
echo ""

# ── 4. Write .env.deploy ──────────────────────────────────────────────────────
echo "▶ 4/4 — Writing .env.deploy (used by next deployment scripts) …"

cat > .env.deploy <<EOF
# ── Auto-generated by gcp_setup.sh ──
# Source this file before running deploy scripts:
#   source .env.deploy
GCP_PROJECT_ID=${GCP_PROJECT_ID}
GCP_REGION=${GCP_REGION}
GCS_STAGING_BUCKET=${GCS_STAGING_BUCKET}
EOF


echo "  ✓ Written: .env.deploy"
echo ""

# ── Done ──────────────────────────────────────────────────────────────────────
echo "╔══════════════════════════════════════════════════════╗"
echo "║   ✅  GCP setup complete!                            ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "  ── Next steps ────────────────────────────────────────"
echo ""
echo "  Step 2 — Authenticate with GCP (Application Default Credentials):"
echo "    gcloud auth login"
echo "    gcloud auth application-default login"
echo "    (This replaces the need for a GEMINI_API_KEY)"
echo ""
echo "  Step 3 — Deploy ADK agents to Agent Engine:"
echo "    source .env.deploy"
echo "    bash deploy_agent_engine.sh"
echo ""
echo "  Step 4 — Sanity test the deployed agent:"
echo "    python sanity_test.py \\"
echo "        --project=\$GCP_PROJECT_ID \\"
echo "        --region=\$GCP_REGION \\"
echo "        --agent-id=<resource-id-from-step-3> \\"
echo "        --skip-cloud-run"
echo ""
